install:
  - mkdir -p ~/.ssh
  - ssh-keygen -t rsa -f ~/.ssh/id_rsa -q -N ""
  - wget http://get.docker.io/ubuntu/pool/main/l/lxc-docker-1.4.1/lxc-docker-1.4.1_1.4.1_amd64.deb
  - sudo dpkg -i lxc-docker-1.4.1_1.4.1_amd64.deb
  - sudo apt-get -fy install
  - sudo apt-get -y install cgroup-lite
  - sudo ln -s /usr/bin/docker /usr/bin/docker.io
  - sudo apt-get install -y slirp
  - git clone git://github.com/jpetazzo/sekexe
before_script:
  - sudo sekexe/run "docker -d &" &
script:
  - sudo sekexe/run "docker pull coopernurse/barrister-conform"
  - sudo sekexe/run "docker run coopernurse/barrister-conform"
after_script:
  - sudo kill `sudo jobs`
